#!/bin/bash
mkdir -p build
for fkb in keyboards/*.def; do
	package=$(grep -m 1 '^#[[:space:]]\+package:' "$fkb" | sed 's/^#[[:space:]]\+package:[[:space:]]*//')
	title=$(grep -m 1 '^#[[:space:]]\+title:' "$fkb" | sed 's/^#[[:space:]]\+title:[[:space:]]*//')
	lang=$(grep -m 1 '^lang[[:space:]]' "$fkb" | sed 's/^.*lang[[:space:]]\+"\([^"]*\)".*$/\1/')
	name="keyboard-$package"
	echo $name
	echo "$lang.vkb:	../$fkb" > build/Makefile
	echo "	../vkb_compiler ../$fkb $lang.vkb" >> build/Makefile
	rm -rf debian
	cp -r debian.in debian
	for f in debian/*; do
		sed -i -e "s/@@NAME@@/$name/g" -e "s/@@TITLE@@/$title/g" -e "s/@@LANG@@/$lang/g" "$f"
	done
	grep '^#[[:space:]]\+desc:' "$fkb" | sed 's/^#[[:space:]]\+desc:[[:space:]]*/ /' >> debian/control
	dpkg-buildpackage -rfakeroot
done
exit 0
